# Generated by Django 5.1.1 on 2024-10-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_userfollows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_img/'),
        ),
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
